# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Accelerometer-Gyroscope' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Pods for Accelerometer-Gyroscope
  pod 'CocoaAsyncSocket' 
  target 'Accelerometer-GyroscopeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Accelerometer-GyroscopeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
